INSERT INTO file_info(file_id, file_name, file_location, longest_word, shortest_word, length, average_word_length)
VALUES (1,
        'example',
        'C://',
        'longword',
        'ok',
        20,
        7),
        (2,
        'example2',
        'C://example/',
        'longword2',
        'ok2',
        22,
        5);
INSERT INTO line_info(line_id, "content", file_id, longest_word, shortest_word, length, average_word_length)
VALUES (1,
        'example',
        1,
        'longword',
        'ok',
        20,
        7),
        (2,
        'example2',
        1,
        'longword2',
        'ok2',
        22,
        5),
        (3,
        'example3',
        2,
        'longword3',
        'ok3',
        23,
        5);